# Generated by Django 6.0 on 2026-05-29 02:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emissionrecord',
            name='emissions_kg_co2e',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='source_type',
            field=models.CharField(choices=[('SAP', 'SAP'), ('UTILITY', 'UTILITY'), ('TRAVEL', 'TRAVEL')], max_length=50),
        ),
        migrations.AlterField(
            model_name='emissionrecord',
            name='raw_data',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='emissionrecord',
            name='scope',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='emissionrecord',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('APPROVED', 'APPROVED'), ('REJECTED', 'REJECTED'), ('SUSPICIOUS', 'SUSPICIOUS')], default='PENDING', max_length=50),
        ),
    ]
